CREATE DATABASE IF NOT EXISTS BUILD25_DEV_TO_PRODUCTION;
CREATE SCHEMA IF NOT EXISTS DATA;

CREATE OR REPLACE STAGE CUSTOMER_CALLS_EXTERNAL
  URL = 's3://sfquickstarts/extracting-insights-from-multimodal-customer-data/AUDIO_DATA/'
  DIRECTORY = (ENABLE = TRUE);

  CREATE OR REPLACE STAGE audio_files
  URL = 's3://sfquickstarts/extracting-insights-from-multimodal-customer-data/AUDIO_DATA/'
  DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE STAGE CUSTOMER_CALLS
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE);

COPY FILES
  INTO @CUSTOMER_CALLS
  FROM @CUSTOMER_CALLS_EXTERNAL;
