CREATE COMPUTE POOL MLOPS_COMPUTE_POOL_GPU
  MIN_NODES = 1
  MAX_NODES = 2
  INSTANCE_FAMILY = GPU_NV_M;

  -- Grant usage of compute pool to newly created role
GRANT USAGE ON COMPUTE POOL MLOPS_COMPUTE_POOL_GPU to ROLE AICOLLEGE;
GRANT USAGE ON COMPUTE POOL MLOPS_COMPUTE_POOL_GPU to ROLE ACCOUNTADMIN;